### PR TITLE
Rkyv

### PR DESCRIPTION
**Pull request by barvirm**
This is a draft.
There is a problem with `&'static str` which cannot be Archived with Rkyv, so I changed it to String. 

Rkyv is only implemented on `caniuse_browsers` with minimal changes to the source code to compile.

Is this how you imagine the introduction of rkyv?

### CODE REVIEW

**Comment by Boshen** [comment]
👍 behind a feature flag.

**Comment by barvirm** [comment]
> 👍 behind a feature flag.

If I understand correctly, do you want "old" solution with "new" in one repo, but will the new approach be behind the feature flag?

**Comment by overlookmotel** [comment]
Thanks very much for tackling this.

Just to clarify one thing: the original intent for using rkyv was primarily to reduce compile time, not run time. Though we should be able to improve run time too by removing the `OnceLock`.

The way I imagined it working is along the lines of https://github.com/oxc-project/oxc-browserslist/issues/23#issuecomment-2143524084. We should if possible avoid using `archived.deserialize()`, as that has a run time cost.

When I said "deserialize" in the comment linked to above, I meant the zero copy deserialization method that rkyv offers, where you don't use a `deserialize` call, and just cast a pointer (so its essentially free). The main difference is that with the zero copy approach, you then have to work with the "archived" types rather than the original types. rkyv's docs unfortunately aren't entirely clear on this, so feel free to ask if it doesn't make sense to you.

**Comment by barvirm** [comment]
> Thanks very much for tackling this.
> 
> Just to clarify one thing: the original intent for using rkyv was primarily to reduce compile time, not run time. Though we should be able to improve run time too by removing the `OnceLock`.
> 
> The way I imagined it working is along the lines of [#23 (comment)](https://github.com/oxc-project/oxc-browserslist/issues/23#issuecomment-2143524084). We should if possible avoid using `archived.deserialize()`, as that has a run time cost.
> 
> When I said "deserialize" in the comment linked to above, I meant the "zero copy deserialization method" that rkyv offers, which isn't really deserialization at all in the usual sense. You don't call `deserialize`, and just cast a pointer (so its essentially free). The main difference is that with the zero copy approach, you then have to work with the "archived" types rather than the original types. rkyv's docs unfortunately aren't entirely clear on this, so feel free to ask if it doesn't make sense to you.

I understand that, I didn't wanna pollute this MR to change all types from &'static str and String to rkyv::ArchivedString etc.

**Comment by Boshen** [comment]
Oh, I'm not familiar with `rkyv` to make a judgement here. The goal here is to reduce binary size and compile time. Run time performance will be negligible because it's mostly called once during the lifetime of a bundler.

So I'll let you make the judgement on this criteria.

(Please ignore my "behind a feature flag" comment).

**Comment by overlookmotel** [comment]
Just to say sorry have not come back to you yet. Have been tied up working on the next phase of Oxc's transformer. Will take a proper look and come back to you as soon as I can. If I forget, please feel free to ping me!

**Comment by barvirm** [comment]
I finish porting everything to rkyv but I introduce more `OnceLock`. I'm not sure how I should get rid of them. I have to clean up some derives on types. But do you have any improvements in mind?

**Comment by overlookmotel** [comment]
> The build time of oxc-browserslist without dependencies is 2.7s from 5.7s (master).
> Release "binary" size libbrowserslist.rlib is 5.3MB from 12MB (master)

Impressive!

Could you possibly try to fix the CI failures? Looks like all that's required is deriving `Debug` on `semver::Version`, and adding `#[allow(unsafe_code)]` attrs to the unsafe `rkyv::archived_root` calls. Once the tests are all passing, it'll be easier to review.

I did not realize that rkyv doesn't have an "archived" version of `&str`. That's an annoyance.

Obviously the runtime perf regressions are a bit of a problem. I'll need to look into this more deeply to understand where that is coming from. If we can figure out a route to fixing that, we could potentially merge this PR and then iterate on it to win the runtime performance back. But we'll need to do *something* about it.

**Comment by barvirm** [comment]
I fixed the CI failures.

**Comment by barvirm** [comment]
I see that some tests are not working. I have problems even on main, when I run: `cargo codegen; cargo build; cargo test` on `main` branch I get: `test result: FAILED. 48 passed; 201 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.14s `.

When I do the test on WLS it is better but I still cannot get all the tests to work:
`test result: FAILED. 217 passed; 32 failed; 0 ignored; 0 measured; 0 filtered out; finished in 14.39s`

**Comment by barvirm** [comment]
I have the same test output on Rkyv branch as on the main under WLS: `test result: FAILED. 217 passed; 32 failed; 0 ignored; 0 measured; 0 filtered out; finished in 14.39s`

**Comment by overlookmotel** [comment]
The test failures appear to be unrelated to content of this PR. I can reproduce the same errors on main: #61. Let's fix that first - hopefully won't take long.

In meantime, if you want to get the tests passing on this branch:

* Merge latest main into this branch
* Alter version of `caniuse-db` in `package.json` to 1.0.30001639.
* `pnpm install`
* `cargo codegen`

The tests then pass.

**Comment by Boshen** [comment]
For the record, where (which project) is `rkyv` is going to be used?

**Pull request closed without merging**
